permissions:
  contents: read
name: Epic Games
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch free games promotion data
        uses: githubocto/flat@v3
        with:
          http_url: https://store-site-backend-static-ipv4.ak.epicgames.com/freeGamesPromotions
          downloaded_filename: public/data/epicgames.json
