name: Scrape Data
on:
    workflow_dispatch:
    schedule:
      - cron: '*/30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      
      - name: Fetch latest data
        run: |-
          curl https://store-site-backend-static-ipv4.ak.epicgames.com/freeGamesPromotions | jq . > public/data/epicgames.json
      
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push